
{{ if or (eq .Values.global.deployment_type "local")  (eq .Values.global.deployment_type "test") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pg-pv
  labels:
    app: database
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/postgres-data-6"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pg-pvc
  labels:
    app: database
spec:
  storageClassName: manual
  volumeName: {{ .Release.Name }}-pg-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ else }}
# assuming gcp
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pg-pvc
  labels:
    app: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
{{ end }}