apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pg-secret
stringData:
  POSTGRES_DB: {{ .Values.database.default_secrets.POSTGRES_DB | quote}}
  POSTGRES_USER: {{ .Values.database.default_secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.database.default_secrets.POSTGRES_PASSWORD | quote}}
  PAL_SVC_PASSWORD: {{ .Values.database.default_secrets.PAL_SVC_PASSWORD | quote}}