#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE ROLE pal_svc WITH LOGIN PASSWORD '$PAL_SVC_PASSWORD';
\connect pal;
GRANT ALL PRIVILEGES ON DATABASE pal TO pal_svc;
GRANT ALL PRIVILEGES ON SCHEMA app TO pal_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA app TO pal_svc;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA app TO pal_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO pal_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO pal_svc;
EOSQL
