apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pal
  template:
    metadata:
      labels:
        app: pal
    
    spec:
      containers:
      - name: pal
        {{ if eq .Values.global.deployment_type "test" }}
        image: pal:latest
        imagePullPolicy: Never
        {{ else }}
        image: us-west3-docker.pkg.dev/pal-ed/pal-images/pal:latest
        imagePullPolicy: Always
        {{ end }}
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-pal-secret

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 15
            
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "512Mi"
          