apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pal-secret
stringData:
  POSTGRES_DB: {{ .Values.database.default_secrets.POSTGRES_DB | quote}}
  POSTGRES_USER:  {{ .Values.database.default_secrets.POSTGRES_USER | quote}}
  POSTGRES_PASSWORD: {{ .Values.database.default_secrets.POSTGRES_PASSWORD | quote}}
  PAL_SVC_PASSWORD: {{ .Values.database.default_secrets.PAL_SVC_PASSWORD | quote }}
  {{ if .Values.global.use_local_llm }}
  OLLAMA_BASE_URL: http://{{ .Release.Name }}-ollama-svc:11434
  {{ else }}
  OPENAI_API_KEY: {{ .Values.pal_app.default_secrets.OPENAI_API_KEY | quote }}
  {{ end }}
  DB_HOST: {{ .Release.Name }}-pg-svc 
  DB_NAME: {{ .Values.pal_app.default_secrets.DB_NAME | quote}}
  DB_USER: {{ .Values.pal_app.default_secrets.DB_USER | quote}}
  DB_PASSWORD: {{ .Values.pal_app.default_secrets.DB_PASSWORD | quote}}
